PRODUCT_SOONG_NAMESPACES += \
                      vendor/gapps

PRODUCT_PACKAGES += \
               AndroidAutoPrebuiltStub \
               GoogleFeedback \
               GoogleOneTimeInitializer \
               GoogleExtServices \
               Phonesky \
               AndroidMigratePrebuilt \
               GooglePackageInstaller \
               SetupWizard \
               GoogleServicesFramework \
               GoogleBackupTransport \
               WellbeingPrebuilt \
               ConfigUpdater \
               PrebuiltGmsCore \
               Turbo \
               GooglePartnerSetup \
               GoogleRestore \
               MarkupGoogle \
               SoundPickerPrebuilt \
               GoogleTTS \
               GoogleContactsSyncAdapter \
               GoogleExtShared \
               GoogleCalendarSyncAdapter \
               WellbeingOverlay \
               PlayStoreOverlay \
               CarrierSetup \
               Photos

PRODUCT_COPY_FILES += \
    vendor/gapps/system/etc/sysconfig/google-hiddenapi-package-whitelist.xml:system/etc/sysconfig/google-hiddenapi-package-whitelist.xml \
    vendor/gapps/system/etc/sysconfig/pixel_2018_exclusive.xml:system/etc/sysconfig/pixel_2018_exclusive.xml \
    vendor/gapps/system/etc/sysconfig/google.xml:system/etc/sysconfig/google.xml \
    vendor/gapps/system/etc/sysconfig/google_exclusives_enable.xml:system/etc/sysconfig/google_exclusives_enable.xml \
    vendor/gapps/system/etc/sysconfig/pixel_experience_2018.xml:system/etc/sysconfig/pixel_experience_2018.xml \
    vendor/gapps/system/etc/sysconfig/pixel_experience_2017.xml:system/etc/sysconfig/pixel_experience_2017.xml \
    vendor/gapps/system/etc/sysconfig/dialer_experience.xml:system/etc/sysconfig/dialer_experience.xml \
    vendor/gapps/system/etc/sysconfig/google_build.xml:system/etc/sysconfig/google_build.xml \
    vendor/gapps/system/etc/sysconfig/nexus.xml:system/etc/sysconfig/nexus.xml \
    vendor/gapps/system/etc/default-permissions/default-permissions.xml:system/etc/default-permissions/default-permissions.xml \
    vendor/gapps/system/etc/default-permissions/opengapps-permissions-q.xml:system/etc/default-permissions/opengapps-permissions-q.xml \
    vendor/gapps/system/etc/permissions/split-permissions-google.xml:system/etc/permissions/split-permissions-google.xml \
    vendor/gapps/system/etc/permissions/privapp-permissions-google.xml:system/etc/permissions/privapp-permissions-google.xml \
    vendor/gapps/system/etc/permissions/com.google.android.media.effects.xml:system/etc/permissions/com.google.android.media.effects.xml \
    vendor/gapps/system/etc/permissions/com.google.android.dialer.support.xml:system/etc/permissions/com.google.android.dialer.support.xml \
    vendor/gapps/system/etc/permissions/com.google.android.maps.xml:system/etc/permissions/com.google.android.maps.xml \
    vendor/gapps/system/etc/preferred-apps/google.xml:system/etc/preferred-apps/google.xml \
    vendor/gapps/system/lib/libsketchology_native.so:system/lib/libsketchology_native.so \
    vendor/gapps/system/usr/srec/en-US/offline_action_data.pb:system/usr/srec/en-US/offline_action_data.pb \
    vendor/gapps/system/usr/srec/en-US/lstm_model.uint8.data:system/usr/srec/en-US/lstm_model.uint8.data \
    vendor/gapps/system/usr/srec/en-US/endpointer_model:system/usr/srec/en-US/endpointer_model \
    vendor/gapps/system/usr/srec/en-US/portable_lstm:system/usr/srec/en-US/portable_lstm \
    vendor/gapps/system/usr/srec/en-US/embedded_class_denorm.mfar:system/usr/srec/en-US/embedded_class_denorm.mfar \
    vendor/gapps/system/usr/srec/en-US/SONG_NAME.fst:system/usr/srec/en-US/SONG_NAME.fst \
    vendor/gapps/system/usr/srec/en-US/endpointer_model.mmap:system/usr/srec/en-US/endpointer_model.mmap \
    vendor/gapps/system/usr/srec/en-US/skip_items_bias.fst:system/usr/srec/en-US/skip_items_bias.fst \
    vendor/gapps/system/usr/srec/en-US/media_bias.fst:system/usr/srec/en-US/media_bias.fst \
    vendor/gapps/system/usr/srec/en-US/input_mean_std_dev:system/usr/srec/en-US/input_mean_std_dev \
    vendor/gapps/system/usr/srec/en-US/SONG_NAME.syms:system/usr/srec/en-US/SONG_NAME.syms \
    vendor/gapps/system/usr/srec/en-US/endpointer_voicesearch.config:system/usr/srec/en-US/endpointer_voicesearch.config \
    vendor/gapps/system/usr/srec/en-US/g2p_graphemes.syms:system/usr/srec/en-US/g2p_graphemes.syms \
    vendor/gapps/system/usr/srec/en-US/monastery_config.pumpkin:system/usr/srec/en-US/monastery_config.pumpkin \
    vendor/gapps/system/usr/srec/en-US/CONTACT_NAME.fst:system/usr/srec/en-US/CONTACT_NAME.fst \
    vendor/gapps/system/usr/srec/en-US/hmm_symbols:system/usr/srec/en-US/hmm_symbols \
    vendor/gapps/system/usr/srec/en-US/lexicon.U.fst:system/usr/srec/en-US/lexicon.U.fst \
    vendor/gapps/system/usr/srec/en-US/commands.abnf:system/usr/srec/en-US/commands.abnf \
    vendor/gapps/system/usr/srec/en-US/contacts.abnf:system/usr/srec/en-US/contacts.abnf \
    vendor/gapps/system/usr/srec/en-US/metadata:system/usr/srec/en-US/metadata \
    vendor/gapps/system/usr/srec/en-US/rescoring.fst.compact:system/usr/srec/en-US/rescoring.fst.compact \
    vendor/gapps/system/usr/srec/en-US/am_phonemes.syms:system/usr/srec/en-US/am_phonemes.syms \
    vendor/gapps/system/usr/srec/en-US/offensive_word_normalizer.mfar:system/usr/srec/en-US/offensive_word_normalizer.mfar \
    vendor/gapps/system/usr/srec/en-US/semantics.pumpkin:system/usr/srec/en-US/semantics.pumpkin \
    vendor/gapps/system/usr/srec/en-US/app_bias.fst:system/usr/srec/en-US/app_bias.fst \
    vendor/gapps/system/usr/srec/en-US/contacts_disambig.fst:system/usr/srec/en-US/contacts_disambig.fst \
    vendor/gapps/system/usr/srec/en-US/g2p_fst:system/usr/srec/en-US/g2p_fst \
    vendor/gapps/system/usr/srec/en-US/ep_portable_model.uint8.mmap:system/usr/srec/en-US/ep_portable_model.uint8.mmap \
    vendor/gapps/system/usr/srec/en-US/g2p.data:system/usr/srec/en-US/g2p.data \
    vendor/gapps/system/usr/srec/en-US/endpointer_dictation.config:system/usr/srec/en-US/endpointer_dictation.config \
    vendor/gapps/system/usr/srec/en-US/transform.mfar:system/usr/srec/en-US/transform.mfar \
    vendor/gapps/system/usr/srec/en-US/g2p_phonemes.syms:system/usr/srec/en-US/g2p_phonemes.syms \
    vendor/gapps/system/usr/srec/en-US/wordlist.syms:system/usr/srec/en-US/wordlist.syms \
    vendor/gapps/system/usr/srec/en-US/c_fst:system/usr/srec/en-US/c_fst \
    vendor/gapps/system/usr/srec/en-US/phonelist:system/usr/srec/en-US/phonelist \
    vendor/gapps/system/usr/srec/en-US/CONTACT_NAME.syms:system/usr/srec/en-US/CONTACT_NAME.syms \
    vendor/gapps/system/usr/srec/en-US/confirmation_bias.fst:system/usr/srec/en-US/confirmation_bias.fst \
    vendor/gapps/system/usr/srec/en-US/magic_mic.config:system/usr/srec/en-US/magic_mic.config \
    vendor/gapps/system/usr/srec/en-US/embedded_normalizer.mfar:system/usr/srec/en-US/embedded_normalizer.mfar \
    vendor/gapps/system/usr/srec/en-US/word_confidence_classifier:system/usr/srec/en-US/word_confidence_classifier \
    vendor/gapps/system/usr/srec/en-US/norm_fst:system/usr/srec/en-US/norm_fst \
    vendor/gapps/system/usr/srec/en-US/pumpkin.mmap:system/usr/srec/en-US/pumpkin.mmap \
    vendor/gapps/system/usr/srec/en-US/contacts_bias.fst:system/usr/srec/en-US/contacts_bias.fst \
    vendor/gapps/system/usr/srec/en-US/dict:system/usr/srec/en-US/dict \
    vendor/gapps/system/usr/srec/en-US/portable_meanstddev:system/usr/srec/en-US/portable_meanstddev \
    vendor/gapps/system/usr/srec/en-US/dnn:system/usr/srec/en-US/dnn \
    vendor/gapps/system/usr/srec/en-US/CLG.prewalk.fst:system/usr/srec/en-US/CLG.prewalk.fst \
    vendor/gapps/system/usr/srec/en-US/voice_actions.config:system/usr/srec/en-US/voice_actions.config \
    vendor/gapps/system/usr/srec/en-US/APP_NAME.fst:system/usr/srec/en-US/APP_NAME.fst \
    vendor/gapps/system/usr/srec/en-US/read_items_bias.fst:system/usr/srec/en-US/read_items_bias.fst \
    vendor/gapps/system/usr/srec/en-US/grammar.config:system/usr/srec/en-US/grammar.config \
    vendor/gapps/system/usr/srec/en-US/compile_grammar.config:system/usr/srec/en-US/compile_grammar.config \
    vendor/gapps/system/usr/srec/en-US/time_bias.fst:system/usr/srec/en-US/time_bias.fst \
    vendor/gapps/system/usr/srec/en-US/config.pumpkin:system/usr/srec/en-US/config.pumpkin \
    vendor/gapps/system/usr/srec/en-US/dictation.config:system/usr/srec/en-US/dictation.config \
    vendor/gapps/system/usr/srec/en-US/hmmlist:system/usr/srec/en-US/hmmlist \
    vendor/gapps/system/usr/srec/en-US/voice_actions_compiler.config:system/usr/srec/en-US/voice_actions_compiler.config \
    vendor/gapps/system/usr/srec/en-US/ep_portable_mean_stddev:system/usr/srec/en-US/ep_portable_mean_stddev \
    vendor/gapps/system/usr/srec/en-US/APP_NAME.syms:system/usr/srec/en-US/APP_NAME.syms \
    vendor/gapps/system/lib64/libjni_latinimegoogle.so:system/lib64/libjni_latinimegoogle.so \
    vendor/gapps/system/lib64/libsketchology_native.so:system/lib64/libsketchology_native.so \
    vendor/gapps/system/framework/com.google.android.media.effects.jar:system/framework/com.google.android.media.effects.jar \
    vendor/gapps/system/framework/com.google.android.maps.jar:system/framework/com.google.android.maps.jar \
    vendor/gapps/system/framework/com.google.android.dialer.support.jar:system/framework/com.google.android.dialer.support.jar